name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Code Review Action
        uses: aidar-freeed/ai-codereviewer@v2.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-model: "gpt-4" # Optional: defaults to gpt-4
          openai-temperature: 0.1 # Optional: defaults to 0.1
          review-comment-prefix: "🤖 AI Code Review:" # Optional: defaults to "AI Code Review:"
