name: Health Check

on:
  workflow_run:
    workflows: ["Deploy to Heroku"]
    types:
      - completed
  workflow_dispatch:  # Allows manual trigger

jobs:
  health_check:
    name: Check Application Health
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['staging', 'production']
    
    steps:
      - name: Check Health Endpoint - ${{ matrix.environment }}
        id: health_check
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://langchain-search-api${{ matrix.environment == 'staging' && '-staging' || '' }}.herokuapp.com/health
          method: 'GET'
          timeout: 10000
        continue-on-error: true

      - name: Notify on Failure
        if: steps.health_check.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🔴 Health Check Failed - ${{ matrix.environment }}`,
              body: `Health check failed for ${{ matrix.environment }} environment at ${new Date().toISOString()}
              
              Environment: ${{ matrix.environment }}
              URL: https://langchain-search-api${{ matrix.environment == 'staging' && '-staging' || '' }}.herokuapp.com/health
              
              Please check the application logs in Heroku dashboard for more details.`
            });
            
            console.log(`Created issue #${issue.data.number}`);

      - name: Check Response
        if: steps.health_check.outcome == 'success'
        run: |
          response='${{ steps.health_check.outputs.response }}'
          if [[ $response != *"healthy"* ]]; then
            echo "Health check response does not indicate healthy status"
            exit 1
          fi 